# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d41f42c539f5fe8bc3f837dd9f079b2af4b6fa6fb0810a7f985f5207e727d5b9ade975f9407f64945e92559eca17e9622306edd0157b6ac378697cbd77b47db2

test:
  secret_key_base: 094377098a30bf5248889e3f508fa8ed2532ca58f8bdfe5c9f9eb55214f758d5f2366d4c3df501270cdc6fb983209c49970c3ef03d01fc627b1eb621562a685c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
